---
title: "main"
output: html_document
---

# Step 1 - Load libraries and source code

```{r, warning=FALSE, message = FALSE}

if (!require("devtools")) install.packages("devtools")
if (!require("pacman")) {
  ## devtools is required
  library(devtools)
  install_github("trinker/pacman")
}

pacman::p_load(knitr, readr, stringr, tesseract, vecsets)

library(stringr)
library(topicmodels)
library(tm)
library(tidytext)
library(dplyr)
library(ldatuning)
library(SnowballC)  
library(NLP)
library(tm)
library(Hmisc)
library(R.oo)

source('../lib/Detection.R')
source('../lib/candidate_vector.R')
source('../lib/dtm.R')
source('../lib/candidate_word_score.R')
source('../lib/confusion_matrix.R')
source('../lib/get_letterlist.R')

```
```{r}

#outputs steps 2,3

#load("../output/tesseract_error.Rdata") #ocr.error
#load("../output/tesseract_correct.Rdata") #ocr.correct
#load("../output/tesseract_full_data.Rdata") #ocr.all.text
#load("../output/ground_truth_full_data.Rdata") #ground.truth.all.text
#load("../output/candidates_list.Rdata") #candidates.list
#load("../output/candidates_list_nonempty.Rdata") #candidates.list.nonempty
#load("../output/ocr_true_error_nonempty.Rdata") #ocr.true.error.nonempty
#load("../output/ocr_final_output.Rdata") #ocr.final.output

```

# Step 2 - Error detection

```{r}
file.name.vector <- list.files("../data/ground_truth")

ground.truth.all = c()
for (doc in 1:length(file.name.vector)){
  ground.truth.text.vector = readLines(paste("../data/ground_truth/", file.name.vector[doc],sep=""))
  ground.truth.all = c(ground.truth.all, ground.truth.text.vector)
  ground.truth.all.text = paste(ground.truth.all, collapse = " ")
}

save(ground.truth.all.text, file = "../output/ground_truth_full_data.Rdata")

ocr.all = c()
for (doc in 1:length(file.name.vector)){
  ocr.text.vector = readLines(paste("../data/tesseract/", file.name.vector[doc],sep =""))
  ocr.all = c(ocr.all, ocr.text.vector)
  ocr.all.text = paste(ocr.all, collapse = " ")
}

save(ocr.all.text, file = "../output/tesseract_full_data.Rdata")

ocr.tokens = str_split(ocr.all.text," ")
ocr.tokens.unique = unique(ocr.tokens[[1]])
ocr.boolean.if.clean = lapply(ocr.tokens.unique,Detection)
ocr.boolean.if.clean = unlist(ocr.boolean.if.clean)
ocr.error = ocr.tokens.unique[!ocr.boolean.if.clean] #9418
ocr.correct = ocr.tokens.unique[ocr.boolean.if.clean]

save(ocr.error, file = "../output/tesseract_error.Rdata")
save(ocr.correct, file = "../output/tesseract_correct.Rdata")
```

# Step 3 - Error correction

# Step 3.1 Generate vector of candidate words for each word detected as incorrect.
```{r}
load("../output/tesseract_error.Rdata") #ocr.error
load("../output/tesseract_correct.Rdata") #ocr.correct
load("../output/tesseract_full_data.Rdata") #ocr.all.text
load("../output/ground_truth_full_data.Rdata") #ground.truth.all.text

dictionary = unique(unlist(strsplit(ground.truth.all.text, split = " ")))

dictionary_letters = list()
  for (i in 1:length(dictionary)) {
    add = unique(unlist(strsplit(dictionary[[i]], "")))
    dictionary_letters = unique(c(dictionary_letters, add))
  }

dictionary_letters = sort(unlist(dictionary_letters))

#There is 15% intersection between dictionary and error vector. Removing those.

not.in.dictionary.boolean = which(ocr.error %nin% dictionary)
ocr.true.error = ocr.error[not.in.dictionary.boolean] #8046

#using of grid provides many-fold time optimivation vs for-loop (0.07sec vs 10sec/error.word)
tic  = Sys.time()
candidates.list = lapply(ocr.true.error, get.candidate.vector, dictionary = dictionary, dictionary_letters = dictionary_letters)
toc = Sys.time()
toc-tic 
ocr.true.error.nonempty = ocr.true.error[lapply(candidates.list, length)>0]
length(ocr.true.error.nonempty) #3073
candidates.list.nonempty = candidates.list[lapply(candidates.list, length)>0]
length(candidates.list.nonempty) #3073

save(candidates.list, file = "../output/candidates_list.Rdata")
save(candidates.list.nonempty, file = "../output/candidates_list_nonempty.Rdata")
save(ocr.true.error.nonempty, file = "../output/ocr_true_error_nonempty.Rdata")
```

```{r}
  dictionary_letters = list()
  for (i in 1:length(dictionary)) {
    add = unique(unlist(strsplit(dictionary[[i]], "")))
    dictionary_letters = unique(c(dictionary_letters, add))
  }

dictionary_letters = sort(unlist(dictionary_letters))
```

